#!/bin/bash
# -*- sh -*- #

export _ALIASES_LOADED="TRUE"

# Color test - alias in the top branch for aliases with color, bottom branch
# for no color
if [ -x /usr/bin/dircolors ]; then
    test -r ~/.dircolors && eval "$(dircolors -b ~/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias ll='ls -alF --color=auto'
    alias la='ls -A --color=auto'
    alias l='ls -CF --color=auto'

    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
else
    alias ll='ls -alF'
    alias la='ls -A'
    alias l='ls -CF'
fi

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'

